n = int(input('Digite um número: '))
f = int(input('Quantos elementos? '))
c = 0
f1 = 0
f2 = n
f3 = 0
print(0, n, end=' ')
while c != f:
    c += 1
    f3 = f2 + f1
    print(f3, end=' ')
    f1 = f2
    f2 = f3
