n = int(input('Digite um número: '))
f = int(input('Quantos elementos? '))
c = 2
f1 = 0
f2 = 0
print(0, n, end=' ')
while c != f:
    c += 1
    f2 = n + f1
    print(f2, end=' ')
    f1 = n
    n = f2
